DROP TABLE IF EXISTS customers_transformed;
CREATE TABLE customers_transformed (
  customerID TEXT,
  Churn INTEGER,
  TotalSpend REAL,
  AvgMonthlySpend REAL,
  TenureGroup TEXT,
  NumAddons REAL,
  SeniorCitizen REAL,
  tenure REAL,
  MonthlyCharges REAL,
  TotalCharges REAL,
  gender_Male INTEGER,
  Partner_Yes INTEGER,
  Dependents_Yes INTEGER,
  PhoneService_Yes INTEGER,
  MultipleLines_No phone service INTEGER,
  MultipleLines_Yes INTEGER,
  InternetService_Fiber optic INTEGER,
  InternetService_No INTEGER,
  OnlineSecurity_No internet service INTEGER,
  OnlineSecurity_Yes INTEGER,
  OnlineBackup_No internet service INTEGER,
  OnlineBackup_Yes INTEGER,
  DeviceProtection_No internet service INTEGER,
  DeviceProtection_Yes INTEGER,
  TechSupport_No internet service INTEGER,
  TechSupport_Yes INTEGER,
  StreamingTV_No internet service INTEGER,
  StreamingTV_Yes INTEGER,
  StreamingMovies_No internet service INTEGER,
  StreamingMovies_Yes INTEGER,
  Contract_One year INTEGER,
  Contract_Two year INTEGER,
  PaperlessBilling_Yes INTEGER,
  PaymentMethod_Credit card (automatic) INTEGER,
  PaymentMethod_Electronic check INTEGER,
  PaymentMethod_Mailed check INTEGER
);